### ISSUE TITLE
[GProfile] RegEx

### ISSUE THREAD

**Issue by Menteroth** [Drapersniper/drapercogs#11]
Every time I update DraperBundle it tells me that regex fails.
![image](https://user-images.githubusercontent.com/24851042/79113692-bdfdc700-7d81-11ea-8cca-c11d50cdd689.png)

**Comment by Menteroth** [comment]
```
[2020-04-13 12:20:41] [ERROR] red.downloader: ERROR: Exception:
Traceback (most recent call last):
  File "c:\__\coding\redenv\lib\site-packages\pip\_internal\cli\base_command.py", line 186, in _main
    status = self.run(options, args)
  File "c:\__\coding\redenv\lib\site-packages\pip\_internal\commands\install.py", line 453, in run
    self._handle_target_dir(
  File "c:\__\coding\redenv\lib\site-packages\pip\_internal\commands\install.py", line 506, in _handle_target_dir
    shutil.rmtree(target_item_dir)
  File "C:\Users\Chris\AppData\Local\Programs\Python\Python38\lib\shutil.py", line 731, in rmtree
    return _rmtree_unsafe(path, onerror)
  File "C:\Users\Chris\AppData\Local\Programs\Python\Python38\lib\shutil.py", line 609, in _rmtree_unsafe
    onerror(os.unlink, fullname, sys.exc_info())
  File "C:\Users\Chris\AppData\Local\Programs\Python\Python38\lib\shutil.py", line 607, in _rmtree_unsafe
    os.unlink(fullname)
PermissionError: [WinError 5] ?tkomst nekad: 'C:\\__\\coding\\Soundwave\\cogs\\Downloader\\lib\\regex\\_regex.cp38-win_amd64.pyd'
```

**Comment by Menteroth** [comment]
Oh shit. That's download. Maybe I should ask in main server.

**Comment by Drapersniper** [comment]
Closing as its not something i can handle
