### ISSUE TITLE
Custom channel cog doesnt work

### ISSUE THREAD

**Issue by malvinarum** [Drapersniper/drapercogs#19]
Custom channel cog creates new voice channels but doesnt move the person who triggered the channel creation, and does not delete empty custom channels when people leave it.

**Comment by malvinarum** [comment]
Log:

`Ignoring exception in on_voice_state_update
Traceback (most recent call last):
  File "/home/ckscompanion/redenv/lib/python3.8/site-packages/discord/client.py", line 312, in _run_event
    await coro(*args, **kwargs)
  File "/home/ckscompanion/.local/share/Red-DiscordBot/data/ckscompanion/cogs/CogManager/cogs/draperbundle/customchannels.py", line 253, in on_voice_state_update
    created_channel = await member.guild.create_voice_channel(
  File "/home/ckscompanion/redenv/lib/python3.8/site-packages/discord/guild.py", line 889, in create_voice_channel
    channel = VoiceChannel(state=self._state, guild=self, data=data)
  File "/home/ckscompanion/redenv/lib/python3.8/site-packages/discord/channel.py", line 553, in __init__
    self._update(guild, data)
  File "/home/ckscompanion/redenv/lib/python3.8/site-packages/discord/channel.py", line 584, in _update
    self._fill_overwrites(data)
  File "/home/ckscompanion/redenv/lib/python3.8/site-packages/discord/abc.py", line 294, in _fill_overwrites
    self._overwrites.append(_Overwrites(id=overridden_id, **overridden))
TypeError: __new__() got an unexpected keyword argument 'allow_new'`

**Comment by Drapersniper** [comment]
issue was an outdated bot install.
