### ISSUE TITLE
Quotes Cog - Error in command 'quoteset channel'

### ISSUE THREAD

**Issue by MK99MA** [Drapersniper/drapercogs#2]
Since my member were asking for a quote-command I was happy to find your repo application and your quotes cog.

I guess I have to whitelist channels to listen to with the "quoteset channel #channel" command, but it keeps giving me an error (Error in command 'quoteset channel'. Check your console or logs for details.) as soon as I use it.

`[2019-07-08 13:58:16] [ERROR] red: Exception in command 'quoteset channel'
Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.7/site-packages/discord/ext/commands/core.py", line 63, in wrapped
    ret = await coro(*args, **kwargs)
  File "/home/pi/Red-DiscordBot/Scambot-chan/cogs/CogManager/cogs/quotes/quotes.py", line 87, in quoteset_channel
    async with channel_group.channels() as channel_data:
  File "/home/pi/.local/lib/python3.7/site-packages/redbot/core/config.py", line 261, in __getattr__
    raise AttributeError("'{}' is not a valid registered Group or value.".format(item))
AttributeError: 'channels' is not a valid registered Group or value.`

Idk if it is just an issue on my end, but I thought I'd let you know.

**Comment by Drapersniper** [comment]
cog has been depricated
