### ISSUE TITLE
Error.

### ISSUE THREAD

**Issue by skylarr1227** [Drapersniper/drapercogs#3]
I'm getting this ..
`[2020-01-20 21:42:44] [ERROR] red.cogs.adventure: Something went wrong controlling the game
Traceback (most recent call last):
  File "/root/.local/share/Red-DiscordBot/cogs/CogManager/cogs/adventure/adventure.py", line 3212, in _adventure
    reward, participants = await self._simple(ctx, adventure_msg, challenge)
  File "/root/.local/share/Red-DiscordBot/cogs/CogManager/cogs/adventure/adventure.py", line 3326, in _simple
    f"{adventure_msg}{text}\n{random.choice(self.LOCATIONS)}\n"
  File "/usr/lib/python3.8/random.py", line 288, in choice
    i = self._randbelow(len(seq))
TypeError: object of type 'NoneType' has no len()`

**Comment by Drapersniper** [comment]
Are you using a custom theme by any chance? This one it’s baffling because it thinks locations doesn’t exist
