### ISSUE TITLE
gprofile traceback

### ISSUE THREAD

**Issue by malvinarum** [Drapersniper/drapercogs#7]
```
Exception in command 'gprofile update'
Traceback (most recent call last):
  File "/home/ckscompanion/redenv/lib/python3.8/site-packages/discord/ext/commands/core.py", line 83, in wrapped
    ret = await coro(*args, **kwargs)
  File "/home/ckscompanion/.local/share/Red-DiscordBot/data/ckscompanion/cogs/CogManager/cogs/draperbundle/gamingprofile.py", line 146, in _profile_update
    user = await update_profile(self.bot, user, author)
  File "/home/ckscompanion/.local/share/Red-DiscordBot/data/ckscompanion/cogs/CogManager/cogs/draperbundle/utilities.py", line 209, in update_profile
    country = number_list[pred_check.result] if pred_check else None
TypeError: list indices must be integers or slices, not NoneType

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ckscompanion/redenv/lib/python3.8/site-packages/discord/ext/commands/bot.py", line 892, in invoke
    await ctx.command.invoke(ctx)
  File "/home/ckscompanion/redenv/lib/python3.8/site-packages/redbot/core/commands/commands.py", line 799, in invoke
    await super().invoke(ctx)
  File "/home/ckscompanion/redenv/lib/python3.8/site-packages/discord/ext/commands/core.py", line 1234, in invoke
    await ctx.invoked_subcommand.invoke(ctx)
  File "/home/ckscompanion/redenv/lib/python3.8/site-packages/discord/ext/commands/core.py", line 797, in invoke
    await injected(*ctx.args, **ctx.kwargs)
  File "/home/ckscompanion/redenv/lib/python3.8/site-packages/discord/ext/commands/core.py", line 92, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: TypeError: list indices must be integers or slices, not NoneType
```

**Comment by Drapersniper** [comment]
Fixed in https://github.com/Drapersniper/drapercogs/commit/039b900f342de666869e6e7c02b48f98bba2819a
